# netlify.toml
[build]
  # Directory to publish
  publish = "build"
  # Default build command
  command = "npm run build"
  # Directory with serverless functions
  functions = "netlify/functions"

# Handle redirects for SPA routing (using HashRouter so not needed)
# Uncomment if using BrowserRouter instead of HashRouter
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Set environment variables for production
# Warning: These values are visible in your build logs
[build.environment]
  # Default target language (can be overridden by user)
  DEFAULT_TARGET_LANG = "en"

# Cache control headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Disable function bundling for easier debugging
[functions]
  node_bundler = "esbuild"
  
# Function-specific settings for translation function
# Increase timeout for batch translations
[[functions]]
  pattern = "batch-translate"
  included_files = ["!node_modules/@babel/**/*"]
  timeout = 30